import { TopStrip } from "@/components/top-strip";
import { CmdKPalette } from "@/components/cmdk-palette";
import { AppShell, PageHeader } from "@/components/page-header";
import { BragDocActions } from "@/components/brag-doc-actions";
import { eventCount, getCurrentGoal } from "@/lib/store";
import { readLastBragDocument } from "@highli/core/documents";

export const dynamic = "force-dynamic";
export const metadata = { title: "highli — brag doc" };

export default async function BragPage() {
  const total = eventCount();
  const current = getCurrentGoal();
  const brag = await readLastBragDocument();

  return (
    <>
      <TopStrip
        goal={current?.text ?? null}
        level={current?.level}
        skills={current?.skills}
        growthAreas={current?.growthAreas}
      />
      <AppShell width="reader">
        <PageHeader
          eyebrow="Living brag doc"
          title="The running document"
          description={
            <>
              One markdown doc generated by{" "}
              <code className="inline-code">highli brag</code> and updated by{" "}
              <code className="inline-code">highli brag --amend</code>. The AI
              recap lives on Home; this page is the document.
            </>
          }
          meta={
            brag
              ? `Updated through ${brag.manifest.lastRunDate}`
              : `${total.toLocaleString()} source ${total === 1 ? "event" : "events"}`
          }
        />

        <BragDocActions hasDocument={!!brag} />

        {brag ? (
          <article className="document-reader living-document-reader">
            <pre>{brag.content}</pre>
          </article>
        ) : (
          <section className="empty-state">
            <p className="eyebrow-pill">No document yet</p>
            <h2>Generate the living brag doc from the raw timeline.</h2>
            <p>
              Use the button above to create the same living document that the
              CLI writes to <code className="inline-code">~/.highli/brags/brag.md</code>.
              After that, both web and{" "}
              <code className="inline-code">highli brag --amend</code> update
              that same file.
            </p>
          </section>
        )}
      </AppShell>
      <CmdKPalette />
    </>
  );
}
